"""
GET/POST /admin/restaurant/{id}/widget-config (Stage 4 Phase A —
Production Customer Widget). Restaurant-scoped like every other resource
in app/routers/admin.py: reuses get_current_admin + require_restaurant_access,
no new authentication system. widget_key is generated server-side only
— never accepted as input, never regenerated by an update — and is
public (safe to return to any authorized admin caller) but grants no
admin privilege of its own.
"""

from app import models

WIDGET_CONFIG_PUBLIC_FIELDS = {
    "id", "restaurant_id", "widget_key", "welcome_message",
    "primary_language", "logo_url", "accent_color",
    "booking_enabled", "is_active", "created_at", "allowed_origins",
}


def _widget_config_url(restaurant_id):
    return f"/admin/restaurant/{restaurant_id}/widget-config"


# --- Auth / tenant isolation ---

def test_get_requires_a_key_at_all(client):
    response = client.get(_widget_config_url(1))
    assert response.status_code == 401


def test_post_requires_a_key_at_all(client):
    response = client.post(_widget_config_url(1), json={})
    assert response.status_code == 401


def test_scoped_admin_cannot_access_a_restaurant_it_is_not_granted(
    client, second_restaurant, scoped_admin_key
):
    _, headers = scoped_admin_key([1])  # NOT granted second_restaurant
    get_response = client.get(_widget_config_url(second_restaurant), headers=headers)
    assert get_response.status_code == 404

    post_response = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "Hi there!"},
        headers=headers,
    )
    assert post_response.status_code == 404


def test_scoped_admin_can_manage_its_own_granted_restaurant(client, scoped_admin_key):
    _, headers = scoped_admin_key([1])
    response = client.post(
        _widget_config_url(1),
        json={"welcome_message": "Hiya! Ask me anything."},
        headers=headers,
    )
    assert response.status_code == 201
    assert response.json()["restaurant_id"] == 1


def test_superadmin_can_manage_any_restaurant(client, admin_headers, second_restaurant):
    response = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "Welcome!"},
        headers=admin_headers,
    )
    assert response.status_code == 201
    assert response.json()["restaurant_id"] == second_restaurant


def test_unknown_restaurant_returns_404(client, admin_headers):
    response = client.get(_widget_config_url(999999), headers=admin_headers)
    assert response.status_code == 404

    post_response = client.post(_widget_config_url(999999), json={}, headers=admin_headers)
    assert post_response.status_code == 404


# --- Create / get ---

def _delete_the_auto_provisioned_config(db, restaurant_id):
    """
    Every restaurant now gets a default WidgetConfig row automatically
    on creation (see routers/platform_admin.py:create_restaurant) --
    this simulates the "no config exists yet" edge case that can no
    longer happen for a normally-onboarded restaurant, so the
    still-important defensive 404/create-from-scratch code paths stay
    covered.
    """
    db.query(models.WidgetConfig).filter(models.WidgetConfig.restaurant_id == restaurant_id).delete()
    db.commit()


def test_get_before_any_config_created_returns_404(client, admin_headers, second_restaurant, db):
    _delete_the_auto_provisioned_config(db, second_restaurant)
    response = client.get(_widget_config_url(second_restaurant), headers=admin_headers)
    assert response.status_code == 404


def test_create_widget_config_with_defaults(client, admin_headers, second_restaurant, db):
    _delete_the_auto_provisioned_config(db, second_restaurant)
    response = client.post(_widget_config_url(second_restaurant), json={}, headers=admin_headers)
    assert response.status_code == 201
    body = response.json()
    assert body["restaurant_id"] == second_restaurant
    assert body["primary_language"] == "en-GB"
    assert body["booking_enabled"] is True
    assert body["is_active"] is True


def test_new_restaurant_is_auto_provisioned_with_an_inactive_default_widget_config(
    client, admin_headers, second_restaurant
):
    """The actual new behavior: second_restaurant already has a
    WidgetConfig the moment it's created, safely inactive until the
    restaurant admin configures and activates it."""
    response = client.get(_widget_config_url(second_restaurant), headers=admin_headers)
    assert response.status_code == 200
    body = response.json()
    assert body["restaurant_id"] == second_restaurant
    assert body["is_active"] is False
    assert body["primary_language"] == "en-GB"
    assert body["booking_enabled"] is True
    assert body["welcome_message"] is None
    assert body["logo_url"] is None
    assert body["accent_color"] is None
    assert isinstance(body["widget_key"], str) and len(body["widget_key"]) > 10
    assert body["allowed_origins"] == []
    assert body["welcome_message"] is None
    assert body["logo_url"] is None
    assert body["accent_color"] is None
    assert isinstance(body["widget_key"], str) and len(body["widget_key"]) > 10


def test_create_widget_config_with_full_fields(client, admin_headers, second_restaurant):
    response = client.post(
        _widget_config_url(second_restaurant),
        json={
            "welcome_message": "Hiya! Welcome to The Anchor.",
            "primary_language": "en-US",
            "logo_url": "https://example.com/logo.png",
            "accent_color": "#7a2e2e",
            "booking_enabled": False,
            "is_active": False,
        },
        headers=admin_headers,
    )
    assert response.status_code == 201
    body = response.json()
    assert body["welcome_message"] == "Hiya! Welcome to The Anchor."
    assert body["primary_language"] == "en-US"
    assert body["logo_url"] == "https://example.com/logo.png"
    assert body["accent_color"] == "#7a2e2e"
    assert body["booking_enabled"] is False
    assert body["is_active"] is False


def test_get_returns_the_created_config(client, admin_headers, second_restaurant):
    client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "Hello!"},
        headers=admin_headers,
    )
    response = client.get(_widget_config_url(second_restaurant), headers=admin_headers)
    assert response.status_code == 200
    assert response.json()["welcome_message"] == "Hello!"


# --- Widget key generation / uniqueness ---

def test_widget_key_is_generated_automatically(client, admin_headers, second_restaurant):
    response = client.post(_widget_config_url(second_restaurant), json={}, headers=admin_headers)
    assert response.status_code == 201
    assert response.json()["widget_key"].startswith("wgt_")


def test_widget_key_is_never_the_internal_restaurant_id(client, admin_headers, second_restaurant):
    response = client.post(_widget_config_url(second_restaurant), json={}, headers=admin_headers)
    widget_key = response.json()["widget_key"]
    assert widget_key != str(second_restaurant)
    assert str(second_restaurant) not in widget_key.replace("wgt_", "")


def test_widget_keys_are_unique_across_restaurants(client, admin_headers, second_restaurant):
    key_1 = client.post(_widget_config_url(1), json={}, headers=admin_headers).json()["widget_key"]
    key_2 = client.post(
        _widget_config_url(second_restaurant), json={}, headers=admin_headers
    ).json()["widget_key"]
    assert key_1 != key_2


def test_widget_key_at_the_database_level_is_unique(client, admin_headers, db):
    """
    Defense in depth: even if application code ever forgot the
    check-before-insert, the database itself must refuse a duplicate
    widget_key across two DIFFERENT restaurants (same reasoning/shape as
    test_platform_admin.py's duplicate-restaurant-access-grant test) —
    two fresh restaurants are onboarded here so this is isolated from
    the restaurant_id unique constraint, which is a separate concern.
    """
    import pytest
    from sqlalchemy.exc import IntegrityError

    from app import models

    def _onboard(name, email):
        response = client.post(
            "/admin/platform/restaurants",
            json={"name": name, "address": "1 Test St", "phone": "0", "email": email},
            headers=admin_headers,
        )
        assert response.status_code == 201
        return response.json()["restaurant"]["id"]

    restaurant_a = _onboard("Widget Key Uniqueness Test A", "widget-key-test-a@example.com")
    restaurant_b = _onboard("Widget Key Uniqueness Test B", "widget-key-test-b@example.com")

    # Each restaurant is auto-provisioned with its own WidgetConfig on
    # creation now -- cleared here so the inserts below are isolated to
    # the widget_key unique constraint being tested, not restaurant_id's.
    _delete_the_auto_provisioned_config(db, restaurant_a)
    _delete_the_auto_provisioned_config(db, restaurant_b)

    db.add(models.WidgetConfig(restaurant_id=restaurant_a, widget_key="wgt_duplicate_test_value"))
    db.commit()

    db.add(models.WidgetConfig(restaurant_id=restaurant_b, widget_key="wgt_duplicate_test_value"))
    with pytest.raises(IntegrityError):
        db.commit()
    db.rollback()


# --- Duplicate configuration handling (upsert semantics) ---

def test_posting_again_updates_the_existing_config_rather_than_creating_a_second_one(
    client, admin_headers, second_restaurant, db
):
    from app import models

    first = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "First message"},
        headers=admin_headers,
    ).json()

    second = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "Updated message"},
        headers=admin_headers,
    ).json()

    assert second["id"] == first["id"]
    assert second["welcome_message"] == "Updated message"

    count = (
        db.query(models.WidgetConfig)
        .filter(models.WidgetConfig.restaurant_id == second_restaurant)
        .count()
    )
    assert count == 1


def test_posting_again_preserves_the_original_widget_key(client, admin_headers, second_restaurant):
    first = client.post(_widget_config_url(second_restaurant), json={}, headers=admin_headers).json()
    second = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "changed"},
        headers=admin_headers,
    ).json()
    assert second["widget_key"] == first["widget_key"]


def test_partial_update_only_touches_provided_fields(client, admin_headers, second_restaurant):
    client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "Original", "accent_color": "#123456"},
        headers=admin_headers,
    )
    response = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "Changed only this"},
        headers=admin_headers,
    )
    assert response.status_code == 201
    body = response.json()
    assert body["welcome_message"] == "Changed only this"
    assert body["accent_color"] == "#123456"  # untouched by the partial update


def test_empty_string_clears_a_field(client, admin_headers, second_restaurant):
    client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "Something"},
        headers=admin_headers,
    )
    response = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": ""},
        headers=admin_headers,
    )
    assert response.status_code == 201
    assert response.json()["welcome_message"] is None


# --- Validation ---

def test_invalid_logo_url_is_rejected(client, admin_headers, second_restaurant):
    for bad_url in ["javascript:alert(1)", "not a url", "ftp://example.com/logo.png", "//example.com/logo.png"]:
        response = client.post(
            _widget_config_url(second_restaurant),
            json={"logo_url": bad_url},
            headers=admin_headers,
        )
        assert response.status_code == 422, f"expected rejection for {bad_url!r}"


def test_valid_logo_urls_are_accepted(client, admin_headers, second_restaurant):
    for good_url in ["https://example.com/logo.png", "http://example.com/logo.png"]:
        response = client.post(
            _widget_config_url(second_restaurant),
            json={"logo_url": good_url},
            headers=admin_headers,
        )
        assert response.status_code == 201
        assert response.json()["logo_url"] == good_url


def test_invalid_accent_color_is_rejected(client, admin_headers, second_restaurant):
    for bad_color in ["red", "#fff", "7a2e2e", "#gggggg", "#7a2e2e00"]:
        response = client.post(
            _widget_config_url(second_restaurant),
            json={"accent_color": bad_color},
            headers=admin_headers,
        )
        assert response.status_code == 422, f"expected rejection for {bad_color!r}"


def test_valid_accent_color_is_accepted(client, admin_headers, second_restaurant):
    response = client.post(
        _widget_config_url(second_restaurant),
        json={"accent_color": "#7A2E2E"},
        headers=admin_headers,
    )
    assert response.status_code == 201
    assert response.json()["accent_color"] == "#7A2E2E"


def test_overlong_welcome_message_is_rejected(client, admin_headers, second_restaurant):
    from app.schemas import WIDGET_WELCOME_MESSAGE_MAX_LENGTH

    response = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "x" * (WIDGET_WELCOME_MESSAGE_MAX_LENGTH + 1)},
        headers=admin_headers,
    )
    assert response.status_code == 422


def test_overlong_primary_language_is_rejected(client, admin_headers, second_restaurant):
    from app.schemas import WIDGET_LANGUAGE_MAX_LENGTH

    response = client.post(
        _widget_config_url(second_restaurant),
        json={"primary_language": "x" * (WIDGET_LANGUAGE_MAX_LENGTH + 1)},
        headers=admin_headers,
    )
    assert response.status_code == 422


def test_malformed_json_body_is_rejected_cleanly(client, admin_headers, second_restaurant):
    response = client.post(
        _widget_config_url(second_restaurant),
        json={"booking_enabled": "not-a-boolean"},
        headers=admin_headers,
    )
    assert response.status_code == 422


# --- Safe public fields / no leakage ---

def test_response_never_contains_unexpected_fields(client, admin_headers, second_restaurant):
    response = client.post(_widget_config_url(second_restaurant), json={}, headers=admin_headers)
    assert set(response.json().keys()) == WIDGET_CONFIG_PUBLIC_FIELDS


def test_response_never_contains_admin_key_or_any_secret(client, admin_headers, second_restaurant):
    response = client.post(
        _widget_config_url(second_restaurant),
        json={"welcome_message": "hi"},
        headers=admin_headers,
    )
    body_text = str(response.json())
    assert admin_headers["X-Admin-API-Key"] not in body_text
    assert "key_hash" not in body_text
    assert "api_key" not in body_text


def test_widget_key_cannot_be_set_or_overridden_via_request_body(client, admin_headers, second_restaurant):
    response = client.post(
        _widget_config_url(second_restaurant),
        json={"widget_key": "wgt_attacker_supplied_value"},
        headers=admin_headers,
    )
    assert response.status_code == 201
    assert response.json()["widget_key"] != "wgt_attacker_supplied_value"


# --- Never logged ---

def test_admin_key_never_logged(client, admin_headers, second_restaurant, caplog):
    import logging

    with caplog.at_level(logging.DEBUG):
        client.post(
            _widget_config_url(second_restaurant),
            json={"welcome_message": "hi"},
            headers=admin_headers,
        )

    log_text = "\n".join(record.getMessage() for record in caplog.records)
    assert admin_headers["X-Admin-API-Key"] not in log_text
