"""unique constraint on opening hours restaurant and day

Revision ID: 118c78d74706
Revises: fedbf449a8cc
Create Date: 2026-09-06 16:51:06.431057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118c78d74706'
down_revision: Union[str, Sequence[str], None] = 'fedbf449a8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_hours', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_opening_hours_restaurant_day', ['restaurant_id', 'day_of_week'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_hours', schema=None) as batch_op:
        batch_op.drop_constraint('uq_opening_hours_restaurant_day', type_='unique')

    # ### end Alembic commands ###
