"""whatsapp integration

Revision ID: 2c874674f008
Revises: a69ea11ba33a
Create Date: 2026-09-06 18:35:35.456473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c874674f008'
down_revision: Union[str, Sequence[str], None] = 'a69ea11ba33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.String(), nullable=False),
    sa.Column('display_phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_numbers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_numbers_phone_number_id'), ['phone_number_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_whatsapp_numbers_restaurant_id'), ['restaurant_id'], unique=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
        batch_op.create_index('ix_conversations_restaurant_channel_external', ['restaurant_id', 'channel', 'external_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_message_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_external_message_id'), ['external_message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_external_message_id'))
        batch_op.drop_column('external_message_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_restaurant_channel_external')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('whatsapp_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_numbers_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_numbers_phone_number_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_numbers_id'))

    op.drop_table('whatsapp_numbers')
    # ### end Alembic commands ###
