"""widget allowed origins

Revision ID: 656fd0e189ed
Revises: 72ca3aeabb32
Create Date: 2026-09-07 17:37:24.021211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656fd0e189ed'
down_revision: Union[str, Sequence[str], None] = '72ca3aeabb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_allowed_origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_config_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['widget_config_id'], ['widget_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_config_id', 'origin', name='uq_widget_allowed_origins_config_origin')
    )
    with op.batch_alter_table('widget_allowed_origins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_allowed_origins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_allowed_origins_widget_config_id'), ['widget_config_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_allowed_origins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_allowed_origins_widget_config_id'))
        batch_op.drop_index(batch_op.f('ix_widget_allowed_origins_id'))

    op.drop_table('widget_allowed_origins')
    # ### end Alembic commands ###
