"""widget config

Revision ID: 72ca3aeabb32
Revises: 2c874674f008
Create Date: 2026-09-07 16:39:44.107704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ca3aeabb32'
down_revision: Union[str, Sequence[str], None] = '2c874674f008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('widget_key', sa.String(), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('booking_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_configs_restaurant_id'), ['restaurant_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_widget_configs_widget_key'), ['widget_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_configs_widget_key'))
        batch_op.drop_index(batch_op.f('ix_widget_configs_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_widget_configs_id'))

    op.drop_table('widget_configs')
    # ### end Alembic commands ###
