"""subscriptions

Jantar SaaS Phase 1 (schema + plan definitions only; see app/plans.py
and app/models.py:Subscription/SubscriptionEvent). Adds the two new
tables, then backfills one Subscription row per EXISTING restaurant
(plan_code="starter", status="active", billing_provider=NULL, every
other new field NULL/false) so every restaurant has a real row before
any endpoint, admin UI, or usage limiting is added in a later phase.

Restaurant is the v1 billing anchor (one Subscription per restaurant,
not a separate Account/Organization layer) -- no existing table or
column is altered by this migration.

A restaurant onboarded AFTER this migration (routers/platform_admin.py:
create_restaurant) does NOT yet get a Subscription row automatically --
that wiring is a deliberate, separately-tracked gap for a later phase,
not something this migration attempts.

Revision ID: 7459207d9901
Revises: e57da8eef647
Create Date: 2026-09-11 22:06:13.769345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7459207d9901'
down_revision: Union[str, Sequence[str], None] = 'e57da8eef647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_restaurant_id'), ['restaurant_id'], unique=False)
        batch_op.create_index('ix_subscription_events_restaurant_id_created_at', ['restaurant_id', 'created_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('billing_provider', sa.String(), nullable=True),
    sa.Column('provider_customer_id', sa.String(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_provider_customer_id'), ['provider_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_provider_subscription_id'), ['provider_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_restaurant_id'), ['restaurant_id'], unique=True)

    # ### end Alembic commands ###

    # --- Backfill: one Subscription row per existing restaurant ---
    # Lightweight table proxies (not the ORM models, which may change
    # shape in the future) so this backfill keeps working exactly as
    # written regardless of later model changes.
    restaurants = sa.table("restaurants", sa.column("id", sa.Integer))
    subscriptions = sa.table(
        "subscriptions",
        sa.column("restaurant_id", sa.Integer),
        sa.column("plan_code", sa.String),
        sa.column("status", sa.String),
        sa.column("billing_provider", sa.String),
        sa.column("provider_customer_id", sa.String),
        sa.column("provider_subscription_id", sa.String),
        sa.column("current_period_end", sa.DateTime),
        sa.column("cancel_at_period_end", sa.Boolean),
    )

    bind = op.get_bind()
    restaurant_ids = [row[0] for row in bind.execute(sa.select(restaurants.c.id))]
    if restaurant_ids:
        bind.execute(
            sa.insert(subscriptions),
            [
                {
                    "restaurant_id": restaurant_id,
                    "plan_code": "starter",
                    "status": "active",
                    "billing_provider": None,
                    "provider_customer_id": None,
                    "provider_subscription_id": None,
                    "current_period_end": None,
                    "cancel_at_period_end": False,
                }
                for restaurant_id in restaurant_ids
            ],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_provider_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_provider_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.drop_index('ix_subscription_events_restaurant_id_created_at')
        batch_op.drop_index(batch_op.f('ix_subscription_events_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_id'))

    op.drop_table('subscription_events')
    # ### end Alembic commands ###
