"""paddle_webhook_provisioning

Jantar SaaS Phase 4 (Paddle webhook subscription provisioning -- see
app/paddle_webhooks.py and app/routers/paddle.py). Two additive
changes, no existing table or column altered:

  1. Adds subscriptions.provider_price_id (nullable) -- the specific
     Paddle price id ("pri_...") a subscription is currently on, which
     is what app/paddle_webhooks.py:PADDLE_PRICE_ID_TO_PLAN_CODE maps to
     plan_code. billing_provider/provider_customer_id/
     provider_subscription_id already existed (Phase 1); this was the
     one provider-linked field missing to fully record a Paddle
     subscription.

  2. Adds the new paddle_webhook_events table -- a raw Paddle webhook
     notification log, deliberately SEPARATE from the existing
     subscription_events table (whose restaurant_id is NOT NULL): a
     Paddle notification can arrive with no deterministic restaurant to
     attribute it to yet (see app/models.py:PaddleWebhookEvent's
     docstring and app/paddle_webhooks.py's module docstring for why),
     so restaurant_id here is nullable. event_id is unique, giving
     idempotent processing of Paddle's at-least-once webhook delivery;
     provider_subscription_id + occurred_at (indexed together) let
     out-of-order notifications for the same subscription be detected.

Revision ID: e939329b9fc1
Revises: 7459207d9901
Create Date: 2026-09-17 15:47:27.487012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e939329b9fc1'
down_revision: Union[str, Sequence[str], None] = '7459207d9901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paddle_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('provider_subscription_id', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paddle_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paddle_webhook_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_paddle_webhook_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paddle_webhook_events_provider_subscription_id'), ['provider_subscription_id'], unique=False)
        batch_op.create_index('ix_paddle_webhook_events_provider_subscription_id_occurred_at', ['provider_subscription_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_paddle_webhook_events_restaurant_id'), ['restaurant_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_price_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('provider_price_id')

    with op.batch_alter_table('paddle_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paddle_webhook_events_restaurant_id'))
        batch_op.drop_index('ix_paddle_webhook_events_provider_subscription_id_occurred_at')
        batch_op.drop_index(batch_op.f('ix_paddle_webhook_events_provider_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_paddle_webhook_events_id'))
        batch_op.drop_index(batch_op.f('ix_paddle_webhook_events_event_id'))

    op.drop_table('paddle_webhook_events')
    # ### end Alembic commands ###
