"""multi-tenant admin authorization

Revision ID: fedbf449a8cc
Revises: 07a381cdb8c1
Create Date: 2026-09-05 21:14:07.504941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedbf449a8cc'
down_revision: Union[str, Sequence[str], None] = '07a381cdb8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_key_id'), ['key_id'], unique=True)

    op.create_table('admin_restaurant_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user_id', 'restaurant_id', name='uq_admin_restaurant_access')
    )
    with op.batch_alter_table('admin_restaurant_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_restaurant_access_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_restaurant_access_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_restaurant_access_restaurant_id'), ['restaurant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_restaurant_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_restaurant_access_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_admin_restaurant_access_id'))
        batch_op.drop_index(batch_op.f('ix_admin_restaurant_access_admin_user_id'))

    op.drop_table('admin_restaurant_access')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_key_id'))
        batch_op.drop_index(batch_op.f('ix_admin_users_id'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
